## NumPy Exercise
![](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

#### Import NumPy as np

In [2]:
import numpy as np

#### Create an array of 10 zeros 

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [5]:
np.full(10,5)

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

#### Create an array of the integers from 10 to 50

In [8]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [10]:
np.random.ranf(1)

array([0.92695302])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [11]:
np.random.randn(25)

array([ 0.97043312, -1.12065283, -0.91949318,  0.22214261, -1.59330968,
       -0.39104888,  2.59355514,  0.11744645,  1.61639526, -0.97168453,
        1.34619417, -1.35562275, -1.34671943, -0.39209149, -0.08531033,
       -0.21130712,  0.02389232,  1.10509649,  0.34491087,  0.07485268,
        2.34883025, -0.61074944, -0.51846553,  0.68059577,  0.12086715])

#### Create an array of 20 linearly spaced points between 0 and 1:

In [12]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

##### Create some arrays and stack them vertically as well as horizontally.

In [26]:
v1 = np.arange(4)
v2 = np.arange(5,9)
v_stack = np.vstack([v1,v2,v2,v1])
print('Vertically Stacked Array:\n',v_stack,'\n')

x1 = np.ones((4,2))
x2 = np.zeros((4,2))
h_stack = np.hstack((x1,x2))
print('Horizontally Stacked Array:\n',h_stack)

Vertically Stacked Array:
 [[0 1 2 3]
 [5 6 7 8]
 [5 6 7 8]
 [0 1 2 3]] 

Horizontally Stacked Array:
 [[1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [6]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [17]:
mat[3:4,4:]

array([[20]])

In [19]:
mat[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [21]:
mat[-1]

array([21, 22, 23, 24, 25])

In [23]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [8]:
mat[[0,1,2,3,4],[0,1,2,3,4]]

array([ 1,  7, 13, 19, 25])

##### Select such an output from `mat` matrix :
|col4|col5|
|----|----|
|4   |5   |
|19  |20  |
|24  |25  |

In [24]:
mat[[0,3,4],3:]

array([[ 4,  5],
       [19, 20],
       [24, 25]])

##### Select the bottom left 3x3 matrix from the last thrid row.

In [25]:
mat[2:,[0,1,2]]

array([[11, 12, 13],
       [16, 17, 18],
       [21, 22, 23]])

### Now do the following

#### Get the sum of all the values in mat

In [24]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [25]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [26]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

#### Show that: The determinant of an identity matrix is 1.

In [23]:
id_matrix = np.identity(5)
print(id_matrix)
print(f'\nThe determinant of the identity matrix is {np.linalg.det(id_matrix)}')

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

The determinant of the identity matrix is 1.0


![](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)
$End$ $of$ $the$ $notebook..$